export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const ADD_NEW_NOTIFICATION = 'ADD_NEW_NOTIFICATION';
export const CHANGE_NOTIFICATION_STATUS = 'CHANGE_NOTIFICATION_STATUS';
export const READ_NOTIFICATIONS = 'READ_NOTIFICATIONS';
