import { GeneralMethodologyContainer } from "./GeneralMethodology.style";

export default function GeneralMethodology() {
  return (
    <GeneralMethodologyContainer>
      <div className="general-methodology-content">
        <h1>General Methodology</h1>
        <h3>Overview</h3>
        <p>
          B-READY assesses an economy’s business environment by focusing on the
          regulatory framework and the provision of related public services
          directed at firms and markets, as well as the efficiency with which
          regulatory framework and public services are combined in practice.
          B-READY seeks a balanced approach when assessing the business
          environment: between ease of conducting a business and broader private
          sector benefits, between regulatory framework and public services,
          between de jure laws and regulations and de facto practical
          implementation, and between data representativeness and data
          comparability. B-READY covers the areas where it can provide the most
          value added in the context of existing indicators: namely, the
          regulatory framework and related public services at the microeconomic
          level.
        </p>
        <h3>What does B-Ready measure?</h3>
        <p>
          B-READY focuses on ten topics that are organized following the life
          cycle of the firm and its participation in the market while opening,
          operating (or expanding), and closing (or reorganizing) a business.
          The main topics include Business Entry, Business Location, Utility
          Services, Labor, Financial Services, International Trade, Taxation,
          Dispute Resolution, Market Competition, and Business Insolvency.
          Within each topic, considerations relevant to the business environment
          regarding aspects of the adoption of digital technology, environmental
          sustainability, and gender are captured. Based on the data collected,
          B-READY generates scores for each topic area and potentially a set of
          aggregate scores. B-READY collects both de jure information and de
          facto measures. While de jure data are collected from expert
          consultations, de facto data are collected from both expert
          consultations and firm surveys. The latter is a major innovation and
          represents a significant increase in the data available to WBG teams,
          development practitioners, and researchers around the world. Data
          collection and reporting processes are governed by the highest
          possible standards of integrity, including sound data gathering
          processes, robust data safeguards, clear approval protocols,
          transparency and public availability of granular data, and
          replicability of results.
        </p>
        <img
          src="https://www.worldbank.org/content/dam/sites/b-ready/subnational/image/2024/Methodology-general-data-structure.png"
          alt="B-Ready Diagram"
          width="100%"
        />
        <h3>How are data collected?</h3>
        <p>
          Quantifying business environment conditions into corresponding
          measurable indicators is critical for the B-READY benchmarking
          exercise. All data obtained from either experts or firms are collected
          in raw form and then converted to a score that can be combined with
          other scores. The objective of the scoring methodology of raw data is
          to allow for score aggregation that preserves absolute cardinal
          differences, which can be used to compare across economies and over
          time (rather than purely ordinal or relative scoring). The granular
          data produced by the B-READY project are combined to produce a score
          for each of the ten B-READY topics. Every topic score will be
          generated by averaging the scores assigned to each of the three
          pillars (regulatory framework, public services, and efficiency) for
          that topic. For nearly all indicators, the regulatory framework pillar
          captures de jure information, and the public services and efficiency
          pillars capture de facto information. The scoring approach therefore
          provides complementarity between de jure laws and regulations and de
          facto practical implementation.
        </p>
        <p>
          B-READY combines primary data collected from thousands of specialists—
          each an expert in the private sector of a specific economy—with data
          collected directly from businesses operating in that economy. To
          accomplish this, B-READY uses expert questionnaires tailored to the
          B-READY project and{" "}
          <a
            href="https://www.enterprisesurveys.org/en/enterprisesurveys"
            target="_blank"
            rel="noopener noreferrer"
          >
            World Bank Enterprise Surveys
          </a>{" "}
          featuring questions designed to feed into the B-READY assessment.
          Through expert questionnaires, the project obtains detailed
          information from specialists in each topic for indicators in the
          Regulatory Framework and Public Services pillars. Using the{" "}
          <a
            href="https://www.enterprisesurveys.org/en/enterprisesurveys"
            target="_blank"
            rel="noopener noreferrer"
          >
            World Bank Enterprise Surveys
          </a>
          , the project gathers data directly from businesses for indicators in
          the Operational Efficiency pillar.
        </p>
        <p>
          <strong>Source: </strong>
          <a
            href="https://www.worldbank.org/en/businessready/methodology#1"
            rel="noopener noreferrer"
            target="_blank"
          >
            www.worldbank.org
          </a>
        </p>
      </div>
    </GeneralMethodologyContainer>
  );
}
