export default {
  starting_a_business: {
    cost_men: 'The cost for men is the total cost required for five male married entrepreneurs to complete the procedures to incorporate and operate a business. It is calculated as a percentage of income per capita. All the fees and costs associated with completing the procedures to start a business are recorded, including all official fees and fees for legal and professional services, if such services are required by law or commonly used in practice. Only incorporation costs are counted, which excludes value added taxes and bribes.',
    cost_women: 'The cost for women is the total cost required for five female married entrepreneurs to complete the procedures to incorporate and operate a business. It is calculated as a percentage of income per capita. All the fees and costs associated with completing the procedures to start a business are recorded, including all official fees and fees for legal and professional services, if such services are required by law or commonly used in practice. Only incorporation costs are counted, which excludes value added taxes and bribes.',
    paid_in_min_capital: 'The paid-in minimum capital requirement reﬂects the amount that the entrepreneur needs to deposit in a bank or with a third-party before registration or up to three months after incorporation. It is calculated as percentage of income per capita. Any legal limitation of the company’s operations or decisions related to the payment of the minimum capital requirement is recorded. In case the legal minimum capital is provided per share, it is assumed 5 shareholders own the company and the legal minimum capital is multiplied by 5 shares. If an economy requires a minimum capital but allows businesses to pay only a part of it before registration, only this part is recorded.',
    procedures_men: 'The number of procedures for men records all the procedures required in practice for five male married entrepreneurs to start and operate a local limited liability company. A procedure is deﬁned as any interaction of the company founders with external parties.  Both pre- and post-incorporation procedures that are officially required or commonly done in practice are recorded.',
    procedures_women: 'The number of procedures for women records all the procedures required in practice for five female married entrepreneurs to start and operate a local limited liability company. A procedure is deﬁned as any interaction of the company founders with external parties or spouses (if legally required). Both pre- and post-incorporation procedures that are officially required or commonly done in practice are recorded. ',
    search_score: 'The ease of doing business score is the simple average of the scores for each of the Doing Business topics: starting a business, dealing with construction permits, getting electricity, registering property, getting credit, protecting minority investors, paying taxes, trading across borders, enforcing contracts and resolving insolvency. The score is computed based on the methodology in the DB17-20 studies for topics that underwent methodology updates.',
    starting_a_business_score: 'The score for starting a business is the simple average of the scores for each of the component indicators: the procedures, time and cost for an entrepreneur to start and formally operate a business, as well as the paid-in minimum capital requirement. ',
    time_men: "The time for men captures the median duration that business incorporation experts indicate is necessary for five male married entrepreneurs to complete all procedures required to start and operate a business with minimum follow- up and no extra payments.It is calulared in calendar days.The time estimates of all procedures are added to calculate the total time required to start and operate a business, taking into account simultaneity of processes.It is assumed that the minimum time required for each procedure is one day, except for procedures that can be fully completed online, for which the time required is recorded as half a day.",
    time_women: 'The time for women captures the median duration that business incorporation experts indicate is necessary for five female married entrepreneurs to complete all procedures required to start and operate a business with minimum follow-up and no extra payments. It is calulared in calendar days. The time estimates of all procedures are added to calculate the total time required to start and operate a business, taking into account simultaneity of processes. It is assumed that the minimum time required for each procedure is one day, except for procedures that can be fully completed online, for which the time required is recorded as half a day.'
  },
  dealing_with_construction_permits: {
    building_quality_control_index: 'The building quality control index is the sum of the following six indices: quality of building regulations, quality control before construction, quality control during construction, quality control after construction, liability and insurance regimes and professional certifications. The component indicator is computed based on the methodology in the DB16-20 studies.',
    cost: 'The cost records all official costs associated with completing the procedures to legally build a warehouse, including the costs associated with obtaining land use approvals and preconstruction design clearances; receiving inspections before, during and after construction; obtaining utility connections; and registering the warehouse at the property registry. It is calculated as a percentage of the warehouse value. Nonrecurring taxes required for the completion of the warehouse project are also recorded. Sales taxes (such as value added tax) or capital gains taxes are not recorded. Nor are deposits that must be paid up front and are later refunded. ',
    ease_of_dealing_with_construction_permits_score: 'The ranking of economies on the ease of dealing with construction permits is determined by sorting their scores for dealing with construction permits. ',
    procedures: 'The number of procedures records all interactions of the building company’s employees or any party acting on its behalf with external parties, including government agencies, notaries, the land registry, the cadastre, utility companies and public inspectors. Procedures that the company undergoes to connect the warehouse to water and sewerage are included. All procedures that are legally required and that are done in practice by a majority of companies  are counted, even if they may be avoided in exceptional cases.',
    search_score: 'The score for dealing with construction permits is the simple average of the scores for each of the component indicators: the procedures, time, cost to deal with construction permits, as well as the building quality control index that evaluate the quality of building regulations, the strength of quality control and safety mechanisms, liability and insurance regimes and professional certification requirements. The score is computed based on the methodology in the DB16-20 studies.',
    time: 'The time captures the median duration that local experts indicate is necessary to complete a procedure in practice. It is calculated in calendar days. The time estimates of all procedures are added to calculate the total time required to complete each procedure, taking into account simultaneity of processes. It is assumed that the minimum time required for each procedure is one day, except for procedures that can be fully completed online, for which the time required is recorded as half a day. '
  },
  getting_electricity: {
    cost: 'The cost is the total median cost associated with completing the procedures to connect a warehouse to electricity. It is calculated as a percentage of income per capita. All the fees and costs associated with completing the procedures to connect a warehouse to electricity are recorded, including those related to obtaining clearances from government agencies, applying for the connection, receiving inspections of both the site and the internal wiring, purchasing material, getting the actual connection works and paying a security deposit. Bribes are not included.',
    ease_of_getting_electricity_score: '',
    procedures: 'The number of procedures records all the procedures required in practice for businesses to obtain a new electrical connection. A procedure is defined as any interaction of the company’s employees or its main electrician or electrical engineer with external parties, such as the electricity distribution utility, electricity supply utilities, government agencies, electrical contractors and firms. Interactions between company employees and steps related to the internal electrical wiring, such as the design and execution of the internal electrical installation plans, are not counted as procedures. However, internal wiring inspections and certifications that are prerequisites to obtain a new connection are counted as procedures. ',
    reliability_of_supply_and_transparency_of_tariff_index: 'The reliability of supply and transparency of tariff index is calculated on the basis of the following six components: (i) duration and frequency of power outages, (ii) tools to monitor power outages, (iii) tools to restore power supply, (iv) regulatory monitoring of utilities’ performance, (v) financial deterrents aimed at limiting outages, and (vi) transparency and accessibility of tariffs. An economy is eligible to obtain a score on the reliability of supply and transparency of tariffs index only if (i) the utility collects data on all types of outages (average total duration of outages per customer and the average number of outages per customer), including planned and unplanned outages, as well as load shedding, with the minimum outage time of not more than 5 minutes; and (ii) the SAIDI value is below a threshold of 100 hours and the SAIFI value is under 100 outages. The component indicator is computed based on the methodology in the DB16-20 studies.',
    search_score: 'The score for the reliability of supply and transparency of tariff index benchmarks economies with respect to the regulatory best practice on the indicator. The score ranges from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB16-20 studies.',
    time: 'The ease of doing business score is the simple average of the scores for each of the Doing Business topics: starting a business, dealing with construction permits, getting electricity, registering property, getting credit, protecting minority investors, paying taxes, trading across borders, enforcing contracts and resolving insolvency. The score is computed based on the methodology in the DB17-20 studies for topics that underwent methodology updates.'
  },
  registering_property: {
    cost: 'The cost is the total of official costs associated with completing the procedures to transfer the property, expressed as a percentage of the property value, assumed to be equiva­lent to 50 times income per capita. It is calculted as a percentage of the property value. Only official costs required by law are recorded, including fees, transfer taxes, stamp duties and any other payment to the property registry, notaries, public agencies or lawyers. Other taxes, such as capital gains tax or value added tax, are excluded from the cost measure. Both costs borne by the buyer and the seller are included. If cost estimates differ among sources, the median reported value is used.',
    ease_of_registering_property_score: 'The ranking of economies on the ease of registering property is determined by sorting their scores for registering property. ',
    procedures: '',
    quality_of_land_administration_index: '',
    search_score: 'The number of procedures records all the procedures necessary for a business (the buyer) to purchase a property from another business (the seller) and to transfer the property title to the buyer’s name so that the buyer can use the property for expanding its business, use the property as collateral in taking new loans or, if necessary, sell the property to another business. A procedure is defined as any interaction that is legally or in practice required between the buyer, the seller or their agents (if required) and external parties, including government agencies, inspectors, notaries and lawyers.',
    time: 'The time captures the median duration that property lawyers, notaries or registry officials indicate is necessary to complete a procedure. It is calculated in calendar days. The time estimates of all procedures are added to calculate the total time required to obtain transfer the property title, taking into account simultaneity of processes. It is assumed that the minimum time required for each procedure is one day, except for proce­dures that can be fully completed online, for which the time required is recorded as half a day.'
  },
  getting_credit: {
    credit_information_index: '',
    ease_of_getting_credit_score: 'The ranking of economies on the ease of getting credit is determined by sorting their scores for getting credit.',
    legal_rights_index: 'The strength of legal rights index measures whether certain features that facilitate lending exist within the appli­cable collateral and bankruptcy laws. The index ranges from 0 to 10 based on the methodology in the DB05-14 studies.',
    search_score: 'The score for getting credit benchmarks economies with respect to the regulatory best practice on the indicator set. The score is indicated on a scale from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB15-20 studies.',
    sum_getting_credit: ''
  },
  protecting_minority_investors: {
    corporate_transparency_index: 'The extent of corporate transparency index measures the level of information that companies must share regarding their board members, senior executives, annual meetings and audits. This index has seven components: (i) whether Buyer must disclose direct and indirect beneficial ownership stakes representing 5%; (ii) whether Buyer must disclose information about board members’ primary employment and director­ships in other companies; (iii) whether Buyer must disclose the compensation of individual managers; (iv) whether a detailed notice of general meeting must be sent 21 calendar days before the meeting; (v) whether shareholders representing 5% of Buyer’s share capital can put items on the general meeting agenda; (vi) whether Buyer’s annual financial statements must be audited by an external auditor; (vii) whether Buyer must disclose its audit reports to the public. The index is computed based on the methodology in the DB15-20 studies.',
    director_liability_index: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    disclosure_index: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    ownership_and_control_index: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    search_score: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    shareholder_rights_index: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    shareholder_suits_index: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    strength_of_minority_investors_protection_index: 'The strength of minority investor protection index is the sum of the extent of disclosure index, extent of director liability index, ease of shareholder suits index, extent of shareholder rights index, extent of ownership and control index and extent of corporate transparency index. The index is computed based on the methodology in the DB15-20 studies.',
    strength_of_minority_investors_protection_index_score: 'The ranking of economies on the strength of minority shareholder protections is determined by sorting their scores for protecting minority investors. '
  },
  paying_taxes: {
    ease_of_paying_taxes_score: 'The ranking of economies on the ease of paying taxes is determined by sorting their scores for paying taxes. ',
    payments: 'The tax payments capture the total number of taxes and contributions paid, the method of payment, the frequency of payment, and the frequency of ﬁling. It includes taxes withheld by the company, such as sales tax, VAT and employee-borne labor taxes.',
    postfiling_index: 'The score for postfiling index benchmarks economies with respect to the regulatory best practice on the indicator. The score is indicated on a scale from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB17-20 studies.',
    search_score: 'The score for paying taxes is the simple average of the scores for each of the component indicators, the payments, time and total tax and contribution rate for a company to comply with tax laws in an economy, as well as the postfiling procedures to request and process a VAT refund claim and to comply with and complete a corporate income tax correction. The score is computed based on the methodology in the DB17-20 studies.',
    time: 'The time to comply with tax laws measures the time taken to prepare, ﬁle and pay three major types of taxes and contributions: the corporate income tax, value added or sales tax and labor taxes, including payroll taxes and social contributions.',
    time_to_complete_a_corporate_income_tax_audit: 'Time to complete a corporate income tax correction (weeks) (DB17-20 methodology) measures the time to complete a review by the tax authority including a formal tax audit if in 25% or more of cases, a company that voluntarily reports an error in its corporate income tax return and an underpayment of the tax due would be selected for additional review. The component indicator is computed based on the methodology in the DB17-20 studies.',
    time_to_comply_with_corporate_income_tax_audit: 'The time to comply with a corporate income tax correction measures the time spent preparing and submitting the correction, and the time spent preparing information for the tax officers, if, in 25% or more of cases, a company that voluntarily reports an error in its CIT return and an underpayment of the tax due would be selected for additional review. The component indicator is computed based on the methodology in the DB17-20 studies.',
    time_to_comply_with_vat_refund: 'The time to comply with VAT refund measures the time spent preparing and submitting the refund claim and the time spent preparing information for the tax officers, if, in 50% or more of cases, a company that requests a VAT cash refund arising from a capital purchase would be selected for an additional review. The component indicator is computed based on the methodology in the DB17-20 studies.',
    time_to_obtain_vat_refund: 'The time to obtain VAT refund measures the time from purchase of the machine to the date of submission of the refund claim (this is equal to half the filing period), the length of any mandatory period that the excess output VAT must be carried forward before a claim can be made, and the time from the submission of the VAT refund claim to the date the refund is received. If a company that requests a VAT cash refund arising from a capital purchase would be selected for additional review in 50% or more of cases, the duration of the review is included in the time to obtain a VAT refund. The component indicator is computed based on the methodology in the DB17-20 studies.',
    total_tax_and_contribution_rate: 'The total tax and contribution rate measures the amount of taxes and mandatory contributions borne by the business in the second year of operation, expressed as a share of commercial proﬁt. The total amount of taxes and contributions borne is the sum of all the different taxes and contributions payable after accounting for allowable deductions and exemptions. The taxes withheld (such as personal income tax) or collected by the company and remitted to the tax authorities (such as VAT, sales tax or goods and service tax) but not borne by the company are excluded.'
  },
  trading_across_borders: {
    cost_to_export_border_compliance: 'The cost for border compliance to export records the cost associated with compliance with the economy’s customs regulations and with regulations relating to other inspections that are mandatory in order for the export shipment to cross the economy’s border, as well as the time and cost for handling that takes place at its port or border. It is calculated in US dollars. The cost for this segment include the cost for customs clearance and inspection procedures conducted by other agencies. For example, the cost for conducting a phytosanitary inspection would be included here. Informal payments for which no receipt is issued are excluded from the costs recorded. The component indicator is computed based on the methodology in the DB16-20 studies.',
    cost_to_export_documentary_compliance: 'The cost for documentary compliance to export records the cost associated with compliance with the export documentary requirements of all government agencies of the origin economy, the destination economy and any transit economies. It is calculated in UD dollars. The cost for documentary compliance includes the cost for obtaining, preparing, processing, presenting and submitting documents. Insurance cost and informal payments for which no receipt is issued are excluded from the costs recorded. The component indicator is computed based on the methodology in the DB16-20 studies.',
    cost_to_import_border_compliance: 'The cost for border compliance to import records the cost associated with compliance with the economy’s customs regulations and with regulations relating to other inspections that are mandatory in order for the import shipment to cross the economy’s border, as well as the time and cost for handling that takes place at its port or border. It is calculated in US dollars. The cost for this segment include the cost for customs clearance and inspection procedures conducted by other agencies. For example, the cost for conducting a technical standard inspection would be included here. Informal payments for which no receipt is issued are excluded from the costs recorded. The component indicator is computed based on the methodology in the DB16-20 studies.',
    cost_to_import_documentary_compliance: 'The cost for documentary compliance to import records the cost associated with compliance with the import documentary requirements of all government agencies of the origin economy, the destination economy and any transit economies. It is calculated in US dollars. The cost for documentary compliance includes the cost for obtaining, preparing, processing, presenting and submitting documents. Insurance cost and informal payments for which no receipt is issued are excluded from the costs recorded. The component indicator is computed based on the methodology in the DB16-20 studies.',
    ease_of_trading_across_borders_score: 'The ranking of economies on the ease of trading across borders is determined by sorting their scores for trading across borders. ',
    search_score: 'Doing Business measures the time and cost associated with three sets of procedures of exporting and importing goods —documentary compliance, border compliance and domestic transport—within the overall process of exporting or importing a shipment of goods. The score for trading across borders is the simple average of the scores for the time and cost for documentary compliance and border compliance to export and import. It is computed based on the methodology in the DB16-20 studies.',
    time_to_export_border_compliance: 'The score for the time for border compliance to export benchmarks economies with respect to the regulatory best practice on the indicator. The score ranges from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB16-20 studies.',
    time_to_export_documentary_compliance: 'The time for documentary compliance to export records the time associated with compliance with the export documentary requirements of all government agencies of the origin economy, the destination economy and any transit economies. It is calculated in hours.  It includes the time for obtaining documents; preparing documents; processing documents; presenting documents; and submitting documents. All electronic or paper submissions of information requested by any government agency in connection with the shipment are considered to be documents obtained, prepared and submitted during the export process. All documents prepared by the freight forwarder or customs broker for the product and partner pair assumed in the case study are included regardless of whether they are required by law or in practice. The component indicator is computed based on the methodology in the DB16-20 studies.',
    time_to_import_border_compliance: 'The score for the time for border compliance to import benchmarks economies with respect to the regulatory best practice on the indicator. The score ranges from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB16-20 studies.',
    time_to_import_documentary_compliance: 'The score for the time for documentary compliance to import benchmarks economies with respect to the regulatory best practice on the indicator. The score ranges from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB16-20 studies.'
  },
  enforcing_contracts: {
    cost: 'The cost to enforce contracts is recorded as a percentage of the claim value, assumed to be equivalent to 200% of income per capita or $5,000, whichever is greater. Three types of costs are recorded: average attorney fees, court costs and enforcement costs. Bribes are not taken into account.',
    ease_of_enforcing_contracts_score: 'The ranking of economies on the ease of enforcing contracts is determined by sorting their scores for enforcing contracts. ',
    quality_of_judicial_processes_index: 'The score for quality of judicial processes index benchmarks economies with respect to the regulatory best practice on the indicator. The score is indicated on a scale from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance, and is computed based on the methodology in the DB17-20 studies.',
    search_score: 'The score for enforcing contracts is the simple average of the scores for each of the component indicators: the time and cost for resolving a commercial dispute through a local first-instance court, as well as the quality of judicial processes that promotes quality and efficiency in the court system. The score is computed based on the methodology in the DB17-20 studies.',
    time: 'The time to enforce contracts is recorded in calendar days, counted from the moment plaintiff decides to file the lawsuit in court until payment. The average duration of the following three different stages of dispute resolution is recorded: (i) filing and service, (ii) trial and judgment, and (iii) enforcement.'
  },
  resolving_insolvency: {
    ease_of_resolving_insolvency_score: 'The ranking of economies on the ease of resolving insolvency is determined by sorting their scores for resolving insolvency. ',
    recovery_rate: 'The recovery rate is recorded as cents on the dollar recovered by secured creditors through judicial reorganization, liquidation or debt enforcement (foreclosure or receivership) proceedings. The calculation takes into account the outcome: whether the business emerges from the proceedings as a going concern or the assets are sold piecemeal.',
    search_score: 'The score for resolving insolvency is the simple average of the scores for each of the component indicators: the recovery rate of insolvency proceedings involving domestic entities, as well as the strength of the legal framework applicable to judicial liquidation and reorganization proceedings.',
    strength_of_insolvency_framework_index: 'The score for strength of insolvency framework index benchmarks economies with respect to the regulatory best practice on the indicator. The score is indicated on a scale from 0 to 100, where 0 represents the worst regulatory performance and 100 the best regulatory performance.'
  },
}
