export default {
  dealing_with_construction_permits: `
    liability_and_insurance_regimes_index_db16_20
    professional_certifications_index_db16_20
    quality_control_after_construction_index_db16_20
    quality_control_before_construction_index_db16_20
    quality_control_during_construction_index_db16_20
    quality_of_building_regulations_index_db16_20
    rank_dealing_with_construction_permits
    score_building_quality_control_index_db16_20
    score_cost
    score_dealing_with_construction_permits_db06_15
    score_dealing_with_construction_permits_db16_20
    score_procedures
    score_time
  `,
  ease_of_doing_business: `
    ease_of_doing_business_rank
    ease_of_doing_business_score_db10_14
    ease_of_doing_business_score_db15
    ease_of_doing_business_score_db17_20
  `,
  enforcing_contracts: `
    alternative_dispute_resolution_db17_20
    attorney_fees
    case_management_db17_20
    court_automation_db17_20
    court_fees
    court_structure_and_proceedings_db17_20
    enforcement_fees
    enforcement_of_judgment
    filing_and_service
    procedures_db04_15
    rank_enforcing_contracts
    score_cost
    score_enforcing_contracts_db04_15
    score_enforcing_contracts_db17_20
    score_procedures_db04_15
    score_quality_of_judicial_processes_index_db17_20
    score_time
    trial_and_judgment
  `,
  getting_credit: `
    credit_bureau_coverage
    credit_registry_coverage
    depth_of_credit_information_index_db05_14
    getting_credit_total_score_db05_14
    getting_credit_total_score_db15_20
    rank_getting_credit
    score_depth_of_credit_information_index_db05_14
    score_depth_of_credit_information_index_db15_20
    score_getting_credit_db05_14
    score_getting_credit_db15_20
    score_strength_of_legal_rights_index_db05_14
    score_strength_of_legal_rights_index_db15_20
    strength_of_legal_rights_index_db05_14
  `,
  getting_electricity: `
    communication_of_tariffs_and_tariff_changes_db16_20
    financial_deterrents_aimed_at_limiting_outages_db16_20
    mechanisms_for_monitoring_outages_db16_20
    mechanisms_for_restoring_service_db16_20
    minimum_outage_time_db16_20
    price_of_electricity_db16_20
    rank_getting_electricity
    regulatory_monitoring_db16_20
    score_cost
    score_getting_electricity_db10_15
    score_getting_electricity_db16_20
    score_procedures
    score_reliability_of_supply_and_transparency_of_tariff_index_db16_20
    score_time
    system_average_interruption_duration_index_db16_20
    system_average_interruption_frequency_index_db16_20
    total_duration_and_frequency_of_outages_per_customer_a_year_db16_20
  `,
  paying_taxes: `
    labor_tax_and_contributions
    other_taxes
    profit_tax
    rank_paying_taxes
    score_paying_taxes_db06_16
    score_paying_taxes_db17_20
    score_payments
    score_postfiling_index_db17_20
    score_time
    score_time_to_complete_a_corporate_income_tax_correction_db17_20
    score_time_to_comply_with_a_corporate_income_tax_correction_db17_20
    score_time_to_comply_with_vat_refund_db17_20
    score_time_to_obtain_vat_refund_db17_20
    score_total_tax_and_contribution_rate
    time_to_complete_a_corporate_income_tax_correction_db17_20
    time_to_comply_with_a_corporate_income_tax_correction_db17_20
    time_to_comply_with_vat_refund_db17_20
    time_to_obtain_vat_refund_db17_20
  `,
  protecting_minority_investors: `
    ease_of_shareholder_suits_index_db06_14
    ease_of_shareholder_suits_index_db15_20
    extent_of_corporate_transparency_index_db15_20
    extent_of_director_liability_index
    extent_of_disclosure_index
    extent_of_ownership_and_control_index_db15_20
    rank_protecting_minority_investors
    score_ease_of_shareholder_suits_index_db06_14
    score_ease_of_shareholder_suits_index_db15_20
    score_extent_of_corporate_transparency_index_db15_20
    score_extent_of_director_liability_index
    score_extent_of_disclosure_index
    score_extent_of_ownership_and_control_index_db15_20
    score_extent_of_shareholder_rights_index_db15_20
    score_protecting_minority_investors_db06_14
    score_protecting_minority_investors_db15_20
    strength_of_investor_protection_index_db06_14
    strength_of_minority_investor_protection_index_db15_20
  `,
  registering_property: `
    equal_access_to_property_rights_index_db17_20
    geographic_coverage_index_db17_20
    land_dispute_resolution_index_db17_20
    rank_registering_property
    reliability_of_infrastructure_index_db17_20
    score_cost
    score_procedures
    score_quality_of_land_administration_index_db17_20
    score_registering_property_db05_15
    score_registering_property_db17_20
    score_time
    transparency_of_information_index_db17_20
  `,
  resolving_insolvency: `
    commencement_of_proceedings_index_db15_20
    cost
    creditor_participation_index_db15_20
    management_of_debtors_assets_index_db15_20
    outcome
    rank_resolving_insolvency
    recovery_rate
    reorganization_proceedings_index_db15_20
    score_recovery_rate
    score_resolving_insolvency
    score_strength_of_insolvency_framework_index
    strength_of_insolvency_framework_index
    time
  `,
  starting_a_business: `
    cost_men
    cost_women
    paid_in_minimum_capital
    procedures_men
    procedures_women
    rank_starting_a_business
    score_cost_men
    score_cost_women
    score_paid_in_minimum_capital
    score_procedures_men
    score_procedures_women
    score_starting_a_business
    score_time_men
    score_time_women
    time_men
    time_women
  `,
  trading_across_borders: `
    cost_to_export_db06_15
    cost_to_import_db06_15
    documents_to_export_db06_15
    documents_to_import_db06_15
    rank_trading_across_borders
    score_cost_to_export_border_compliance_db16_20
    score_cost_to_export_db06_15
    score_cost_to_export_documentary_compliance_db16_20
    score_cost_to_import_border_compliance_db16_20
    score_cost_to_import_db06_15
    score_cost_to_import_documentary_compliance_db16_20
    score_documents_to_export_db06_15
    score_documents_to_import_db06_15
    score_time_to_export_border_compliance_db16_20
    score_time_to_export_db06_15
    score_time_to_export_documentary_compliance_db16_20
    score_time_to_import_border_compliance_db16_20
    score_time_to_import_db06_15
    score_time_to_import_documentary_compliance_db16_20
    score_trading_across_borders_db06_15
    score_trading_across_borders_db16_20
    time_to_export_db06_15
    time_to_import_db06_15
  `
}